spring:
    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: main
            auto-offset-reset: earliest
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
